**NumPy**

In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.arange(0,110,10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [7]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [8]:
np.full((5,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [9]:
np.full((2,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [13]:
np.random.random((2,2))

array([[0.19812498, 0.39116165],
       [0.59161284, 0.99100641]])

In [20]:
a=np.array(([1,2,3],[4,5,6]))

In [22]:
x=a.shape

In [23]:
list(x)

[2, 3]

In [24]:
a.shape =(3,2)

In [25]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
a.shape =(2,3)

In [27]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
a.shape[0]

2

In [32]:
a.shape[1]

3

In [33]:
x=np.full((5,8),9)

In [34]:
x

array([[9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9]])

In [35]:
x.shape

(5, 8)

In [36]:
x.shape[0]

5

In [37]:
x.shape[1]

8

In [38]:
a.size

6

In [39]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
x.size

40

In [41]:
a=np.arange(10)

In [42]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
x

array([[9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9]])

In [44]:
x.ndim

2

In [45]:
a.ndim

1

In [46]:
a.dtype

dtype('int64')

In [47]:
x.dtype

dtype('int64')

In [50]:
x=np.linspace(1,10,20)

In [51]:
x

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [52]:
x.dtype

dtype('float64')

In [53]:
a=np.arange(9)

In [54]:
a.shape=(3,3)

In [55]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
b=np.full((3),1)

In [60]:
b

array([1, 1, 1])

In [61]:
a+b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
a-b

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [63]:
b-a

array([[ 1,  0, -1],
       [-2, -3, -4],
       [-5, -6, -7]])

In [67]:
x="abin joseph" 

In [68]:
x

'abin joseph'

In [70]:
x[0:4]

'abin'

In [73]:
x[5:11]

'joseph'

In [76]:
x[-6:-1]

'josep'

In [78]:
x[-1:]

'h'

In [80]:
x[::-1]

'hpesoj niba'

In [81]:
x[:-1]

'abin josep'

In [82]:
x[:5]

'abin '

In [84]:
x[5:]

'joseph'

In [87]:
x[:4]

'abin'

In [88]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
a+=1

In [91]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
a[0]

array([1, 2, 3])

In [93]:
a[::1]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
a[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [100]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
a[:2,:2]

array([[1, 2],
       [4, 5]])

In [102]:
a[:2,:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
a[:3,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [104]:
a[:2,:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
a[:1,:1]

array([[1]])

In [106]:
a[:1,:2]

array([[1, 2]])

In [107]:
a[:1,:3]

array([[1, 2, 3]])

In [110]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
a[1]

array([4, 5, 6])

In [112]:
a[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [113]:
a[:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [115]:
a[2:]

array([[7, 8, 9]])

In [116]:
a=np.arange(3)
b=np.arange(3,6)

In [117]:
a

array([0, 1, 2])

In [118]:
b

array([3, 4, 5])

In [119]:
a+=1
b+=1

In [121]:
a

array([1, 2, 3])

In [122]:
b

array([4, 5, 6])

In [126]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [135]:
a=np.arange(6)
b=np.arange(7,13)

In [139]:
a.shape=(3,2)

In [136]:
b.shape=(3,2)

In [140]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [138]:
b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [141]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  7,  8],
       [ 2,  3,  9, 10],
       [ 4,  5, 11, 12]])

In [143]:
np.concatenate((a,b),axis=0)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [144]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [145]:
b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [148]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [149]:
np.hstack((a,b))

array([[ 0,  1,  7,  8],
       [ 2,  3,  9, 10],
       [ 4,  5, 11, 12]])

In [151]:
np.stack((a,b),axis=0)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [155]:
np.stack((a,b),axis=1)

array([[[ 0,  1],
        [ 7,  8]],

       [[ 2,  3],
        [ 9, 10]],

       [[ 4,  5],
        [11, 12]]])

In [157]:
np.column_stack((a,b))

array([[ 0,  1,  7,  8],
       [ 2,  3,  9, 10],
       [ 4,  5, 11, 12]])

In [158]:
np.row_stack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [182]:
a=np.arange(0,6)

In [186]:
a.shape=(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [196]:
np.split(a,2,0)

[array([[0, 1, 2]]), array([[3, 4, 5]])]

In [198]:
np.split(a,3,1)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [200]:
np.split(a,[0,1],0)

[array([], shape=(0, 3), dtype=int64), array([[0, 1, 2]]), array([[3, 4, 5]])]

In [204]:
a=np.arange(9)

In [205]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [206]:
a.shape =(3,3)

In [207]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [208]:
np.split(a,[1,2],0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]